# Generated by Django 2.1.4 on 2018-12-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMustBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片连接地址')),
                ('name', models.CharField(max_length=80, verbose_name='名字')),
                ('trackid', models.CharField(max_length=16, verbose_name='id')),
            ],
            options={
                'verbose_name': '每日必买表',
                'verbose_name_plural': '每日必买表',
                'db_table': 'axf_mustbuy',
            },
        ),
        migrations.CreateModel(
            name='MainNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片连接地址')),
                ('name', models.CharField(max_length=80, verbose_name='名字')),
                ('trackid', models.CharField(max_length=16, verbose_name='id')),
            ],
            options={
                'verbose_name': '导航表',
                'verbose_name_plural': '导航表',
                'db_table': 'axf_nav',
            },
        ),
        migrations.CreateModel(
            name='MainShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片连接地址')),
                ('name', models.CharField(max_length=80, verbose_name='名字')),
                ('trackid', models.CharField(max_length=16, verbose_name='id')),
            ],
            options={
                'verbose_name': '商店商品表',
                'verbose_name_plural': '商店商品表',
                'db_table': 'axf_shop',
            },
        ),
        migrations.AlterField(
            model_name='axf',
            name='trackid',
            field=models.CharField(max_length=16, verbose_name='id'),
        ),
    ]
