# Generated by Django 2.1.4 on 2018-12-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181211_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, verbose_name='图片连接地址')),
                ('name', models.CharField(max_length=80, verbose_name='名字')),
                ('trackid', models.CharField(max_length=16, verbose_name='id')),
                ('categoryid', models.CharField(max_length=20, verbose_name='分类id')),
                ('brandname', models.CharField(max_length=70, verbose_name='商品的名称')),
                ('img1', models.CharField(max_length=255, verbose_name='图片的1id')),
                ('childcid1', models.CharField(max_length=20, verbose_name='商品1的id')),
                ('productid1', models.CharField(max_length=20, verbose_name='商品1的编号')),
                ('longname1', models.CharField(max_length=100, verbose_name='商品1的名称')),
                ('price1', models.FloatField(default=1, verbose_name='商品1的价格')),
                ('marketprice1', models.FloatField(default=1, verbose_name='市场价格1')),
                ('img2', models.CharField(max_length=255, verbose_name='图片的2id')),
                ('childcid2', models.CharField(max_length=20, verbose_name='商品2的id')),
                ('productid2', models.CharField(max_length=20, verbose_name='商品2的编号')),
                ('longname2', models.CharField(max_length=100, verbose_name='商品2的名称')),
                ('price2', models.FloatField(default=1, verbose_name='商品2的价格')),
                ('marketprice2', models.FloatField(default=1, verbose_name='市场价格2')),
                ('img3', models.CharField(max_length=255, verbose_name='图片3的id')),
                ('childcid3', models.CharField(max_length=20, verbose_name='商品3的id')),
                ('productid3', models.CharField(max_length=20, verbose_name='商品3的编号')),
                ('longname3', models.CharField(max_length=100, verbose_name='商品3的名称')),
                ('price3', models.FloatField(default=1, verbose_name='商品3的价格')),
                ('marketprice3', models.FloatField(default=1, verbose_name='市场价格3')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
