# Generated by Django 2.1.4 on 2018-12-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20181211_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(default=1, verbose_name='类型id')),
                ('typename', models.IntegerField(max_length=255, verbose_name='类别名称')),
                ('childtypenames', models.IntegerField(max_length=255, verbose_name='子类名称')),
                ('typesort', models.IntegerField(default=1, verbose_name='类型顺序')),
            ],
            options={
                'verbose_name': '食品类型',
                'verbose_name_plural': '食品类型',
                'db_table': 'axf_foodtypes',
            },
        ),
    ]
