# Generated by Django 2.1.4 on 2018-12-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_mainfoodtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfoodtypes',
            name='childtypenames',
            field=models.CharField(max_length=255, verbose_name='子类名称'),
        ),
        migrations.AlterField(
            model_name='mainfoodtypes',
            name='typename',
            field=models.CharField(max_length=255, verbose_name='类别名称'),
        ),
    ]
